apiVersion: apps/v1
kind: Deployment
metadata:
  name: yw-test-2
  labels:
    app: yw-test-2
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1734448518983
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yw-test-2
  template:
    metadata:
      labels:
        app: yw-test-2
    spec:
      containers:
        - name: yw-test-2
          image: wyregistry.azurecr.io/image-workflow-1734448518983:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
